@php
    /** @var array $contact */
    $name = trim((string) ($contact['name'] ?? ''));
    $department = trim((string) ($contact['department'] ?? ''));
    $email = trim((string) ($contact['email'] ?? ''));
    $phone = trim((string) ($contact['phone'] ?? ''));
    $telHref = $phone === '' ? '' : preg_replace('/\s+/u', '', $phone);
@endphp
<div class="framer-10uymah-container">
    <div class="framer-ZOkOd framer-Kgz85 framer-P94oq framer-28HUQ framer-TdyIu framer-pl6hh3 framer-v-pl6hh3" data-framer-name="default" style="width: 100%; opacity: 1;"><div class="framer-eopnqu" data-framer-name="name + position" style="opacity: 1;"><div class="framer-jr1i8z" data-framer-name="name" style="justify-content: center; --extracted-r6o4lv: var(--token-0698ec6e-98d5-4dc5-82cd-980692a5f3e9, rgb(28, 24, 23)); --framer-paragraph-spacing: 0px; will-change: transform; opacity:0; transform:translateY(40px);" data-framer-component-type="RichTextContainer" data-nce-scroll="true" data-nce-initial-transform="translateY(40px)"><p class="framer-text framer-styles-preset-7ice6b" data-styles-preset="vnnK8mUU3" dir="auto" style="--framer-text-color:var(--extracted-r6o4lv, var(--token-0698ec6e-98d5-4dc5-82cd-980692a5f3e9, rgb(28, 24, 23)))">{{ $name }}</p></div><div class="framer-1c0gtwo" data-framer-name="position" style="justify-content: center; --framer-paragraph-spacing: 0px; will-change: transform; opacity:0; transform:translateY(40px);" data-framer-component-type="RichTextContainer" data-nce-scroll="true" data-nce-initial-transform="translateY(40px)"><p class="framer-text framer-styles-preset-1luqla7" data-styles-preset="c5ZxYZqDW" dir="auto">{{ $department }}</p></div></div><div class="framer-1dcrdre" data-framer-name="email + phone" style="opacity: 1;"><div class="framer-1us0h3u" data-framer-name="email" style="justify-content: center; --extracted-r6o4lv: #c40023; --framer-paragraph-spacing: 0px; will-change: transform; opacity:0; transform:translateY(40px);" data-framer-component-type="RichTextContainer" data-nce-scroll="true" data-nce-initial-transform="translateY(40px)"><p class="framer-text framer-styles-preset-md7q5c" data-styles-preset="zT_YMBz2z" dir="auto" style="--framer-text-color:var(--extracted-r6o4lv, #c40023)">@if ($email !== '')<!--$--><a class="framer-text framer-styles-preset-1x3gsum" data-styles-preset="tHfRgPBHm" href="mailto:{{ e($email) }}" rel="noopener" target="_top">{{ $email }}</a><!--/$-->@endif</p></div><div class="framer-f4unag" data-framer-name="phone" style="justify-content: center; --extracted-r6o4lv: #c40023; --framer-paragraph-spacing: 0px; will-change: transform; opacity:0; transform:translateY(40px);" data-framer-component-type="RichTextContainer" data-nce-scroll="true" data-nce-initial-transform="translateY(40px)"><p class="framer-text framer-styles-preset-md7q5c" data-styles-preset="zT_YMBz2z" dir="auto" style="--framer-text-color:var(--extracted-r6o4lv, #c40023)">@if ($phone !== '')<!--$--><a class="framer-text framer-styles-preset-1x3gsum" data-styles-preset="tHfRgPBHm" href="tel:{{ e($telHref) }}" target="_blank" rel="noopener">{{ $phone }}</a><!--/$-->@endif</p></div></div></div></div>
