@php
    $card = is_array($card ?? null) ? $card : [];
    $title = trim((string) ($card['title'] ?? ''));
    $imgPath = trim((string) ($card['image'] ?? ''));
    $alt = trim((string) ($card['alt'] ?? ''));
    $index = max(1, (int) ($index ?? 1));
    $digits = str_pad((string) $index, 2, '0', STR_PAD_LEFT);
    $fallbackImg = asset('assets/images/10b2101792bd7e4e-iBliZ6U0n2mOK6nHB0zA61chf4.webp');
@endphp
@if ($title !== '')
<div class="framer-fsqugi" data-framer-name="service card"><nav class="framer-c2yqxq" data-framer-name="stack"><div class="framer-1j5eoxv" data-framer-name="Title"><div class="ssr-variant"><div class="framer-1x55gs6-container"><div class="framer-rOBNv framer-LQZ0A framer-1rtee3t framer-v-1rtee3t" data-framer-name="tag" style="opacity: 1;"><div class="framer-1jru3ku" data-border="true" data-framer-appear-id="1jru3ku" data-framer-name="shape" style="--border-bottom-width: 4px; --border-color: var(--token-0cfc16fd-3729-4b64-9ac8-d1037c8fcb3d, rgb(249, 64, 6)); --border-left-width: 4px; --border-right-width: 4px; --border-style: solid; --border-top-width: 4px; border-radius: 56px; opacity: 1; transform: none"></div><div class="framer-12dfj9l" style="opacity: 1;"><div class="framer-1u0caki" data-framer-name="text" style="justify-content: flex-end; --extracted-r6o4lv: var(--variable-reference-Jju9HfMVV-p7bgp70n3); --framer-paragraph-spacing: 0px; --variable-reference-Jju9HfMVV-p7bgp70n3: var(--token-0698ec6e-98d5-4dc5-82cd-980692a5f3e9, rgb(28, 24, 23)); transform: none; opacity: 1;" data-framer-component-type="RichTextContainer"><p class="framer-text framer-styles-preset-ily28r" data-styles-preset="jLcxwmdlI" dir="auto" style="--framer-text-color:var(--extracted-r6o4lv, var(--variable-reference-Jju9HfMVV-p7bgp70n3))"><span style="white-space:nowrap"><span style="display: inline-block; opacity: 1; transform: none">{{ $digits[0] }}</span><span style="display: inline-block; opacity: 1; transform: none">{{ $digits[1] }}</span></span></p></div></div></div></div></div><div class="framer-1dzk6pv" data-framer-name="Stack" style="opacity: 1; transform: none"><div class="framer-tdhj58" data-framer-name="title" style="justify-content:center;transform:none" data-framer-component-type="RichTextContainer"><h5 class="framer-text framer-styles-preset-1m4fxxt" data-styles-preset="IcVUEeNmM" dir="auto" style="--framer-text-color:var(--token-0698ec6e-98d5-4dc5-82cd-980692a5f3e9, rgb(28, 24, 23))">{{ e($title) }}</h5></div></div></div></nav><div class="framer-1vi9ke6" data-framer-name="image"><div class="ssr-variant"><div class="framer-1d10y97-container" data-framer-name="img - service 1" name="img - service 1"><div name="img - service 1" class="framer-Z0z4Z framer-rlntoc framer-v-ut5ihd" data-framer-name="image - start" style="max-height: 100%; width: 100%; border-radius: 8px; opacity: 1;"><figure class="framer-w9jxa7" data-framer-name="image" style="border-radius: 8px; opacity: 1;"><div style="position:absolute;border-radius:inherit;corner-shape:inherit;top:0;right:0;bottom:0;left:0" data-framer-background-image-wrapper="true"><img decoding="auto" loading="lazy" width="2400" height="1600" src="{{ cms_public_url($imgPath !== '' ? $imgPath : null, $fallbackImg) }}" alt="{{ e($alt) }}" style="display:block;width:100%;height:100%;border-radius:inherit;corner-shape:inherit;object-position:center;object-fit:cover"></div></figure></div></div></div></div></div>
@endif
