@php
    $card = is_array($card ?? null) ? $card : [];
    $title = trim((string) ($card['title'] ?? ''));
    $imgPath = trim((string) ($card['image'] ?? ''));
    $alt = trim((string) ($card['alt'] ?? ''));
    $fallbackImg = asset('assets/images/0278e48e56dc2eb3-fTY3jHNvYEyooysxiifTM2xSTfg.jpg');
@endphp
@if ($title !== '')
<div class="ssr-variant hidden-8cyn1i"><div class="framer-mz54bv-container"><div class="framer-jE7hz framer-kyBfp framer-z51kq3 framer-v-z51kq3" data-framer-name="card" style="--e972yo: 32px 24px 32px 24px; width: 100%; border-radius: 8px; opacity: 1;"><div class="framer-1yidbq8" data-framer-name="card bg" style="background-color: var(--token-03addee0-85ca-4632-964b-3ca263d37f6a, rgb(100, 26, 2)); border-radius: 8px; opacity: 1;"></div><div class="framer-6vdlfd" style="opacity: 1;"><div class="framer-7cnrkk-container" data-framer-name="video or image" name="video or image" style="opacity: 1;"><div name="video or image" class="framer-Z0z4Z framer-rlntoc framer-v-ikh08d" data-framer-name="image - end" style="height: 100%; width: 100%; border-radius: 8px; opacity: 1;"><figure class="framer-w9jxa7" data-framer-name="image" style="border-radius: 8px; opacity: 1;"><div style="position:absolute;border-radius:inherit;corner-shape:inherit;top:0;right:0;bottom:0;left:0" data-framer-background-image-wrapper="true"><img decoding="auto" loading="lazy" width="1920" height="1280" src="{{ cms_public_url($imgPath !== '' ? $imgPath : null, $fallbackImg) }}" alt="{{ e($alt) }}" style="display:block;width:100%;height:100%;border-radius:inherit;corner-shape:inherit;object-position:center;object-fit:cover"></div></figure></div></div><div class="framer-yr1l0h" data-framer-name="h5" style="justify-content: center; --extracted-1eung3n: var(--token-93ed733c-d50c-4cfe-9503-161904973ec7, rgb(255, 255, 255)); --framer-paragraph-spacing: 0px; will-change: transform; opacity:0; transform:translateY(40px);" data-framer-component-type="RichTextContainer" data-nce-scroll="true" data-nce-initial-transform="translateY(40px)"><h4 class="framer-text framer-styles-preset-1m4fxxt" data-styles-preset="IcVUEeNmM" dir="auto" style="--framer-text-color:var(--extracted-1eung3n, var(--token-93ed733c-d50c-4cfe-9503-161904973ec7, rgb(255, 255, 255)))">{{ e($title) }}</h4></div></div></div></div></div>
@endif
